# Generated by Django 4.1.4 on 2023-12-01 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudentDataBank', '0003_student_semester'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('number_of_pages', models.IntegerField()),
                ('language', models.CharField(max_length=50)),
                ('genre', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('published', models.DateField()),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='book_covers/')),
            ],
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
