# Generated by Django 4.1.4 on 2023-12-01 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudentDataBank', '0004_book_delete_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='id',
        ),
        migrations.AlterField(
            model_name='book',
            name='name',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
    ]
